### ISSUE TITLE
make a new diceGame with javascript 

### ISSUE THREAD

**Issue by jay08111** [jay08111/diceGame#2]
## description
make a simple dice game with html css javascript 

## Tasks

- [x] make a simple structure
- [x] make with material design
- [x] simple javascript code
